version: "3"
services:
  postfresql:
    container_name: "postgresql-servidor"
    image: "postgres:latest"

    networks:
      - postgresql-network

    ports:
      - "5010:5432"
    
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
#esas dos direcciones hay que buscarlas en windows
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always

networks:
  postgresql-network:
      